apiVersion: v1
kind: Service
metadata:
        name: db-service
        labels:
                app: teammanager
spec:
  ports:
    - port: 27017
  selector:
          app: teammanager
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    app: teammanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teammanager
  template:
    metadata:
      labels:
        app: teammanager
    spec:
      containers:
        - name: mongodb-teammanager
          image: mongo
          ports:
                  - containerPort: 27017