apiVersion: apps/v1
kind: Deployment
metadata:
  name: teammanager-deploy
  labels:
    app: teammanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teammanager
  template:
    metadata:
      labels:
        app: teammanager
    spec:
      containers:
        - name: teammanager
          image: 892266550564.dkr.ecr.eu-west-3.amazonaws.com/jenkins_unir:latest
          env:
            - name: TEAM_MANAGER_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: teammanger-cm
                  key: TEAM_MANAGER_MONGODB_URI
            - name: TEAM_MANAGER_TEST_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: teammanger-cm
                  key: TEAM_MANAGER_TEST_MONGODB_URI
            - name: TEAM_MANAGER_PORT
              valueFrom:
                configMapKeyRef:
                  name: teammanger-cm
                  key: TEAM_MANAGER_PORT
            - name: TEAM_MANAGER_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: teammanger-cm
                  key: TEAM_MANAGER_SECRET_KEY
          ports:
            - containerPort: 4444
