apiVersion: v1
kind: Service
metadata:
  name: teammanager-service
spec:
  selector:
    app: teammanager
  ports:
    - port: 80
      targetPort: 4444
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: teammanager-deploy
  labels:
    app: teammanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teammanager
  template:
    metadata:
      labels:
        app: teammanager
    spec:
      containers:
        - name: teammanager
          image: 892266550564.dkr.ecr.eu-west-3.amazonaws.com/jenkins_unir:latest
          env:
            - name: TEAM_MANAGER_MONGODB_URI
              value: "mongodb://db-service/teammanager"
            - name: TEAM_MANAGER_TEST_MONGODB_URI
              value: "mongodb://db-service/teammanager-test"
            - name: TEAM_MANAGER_PORT
              value: "4444"
            - name: TEAM_MANAGER_SECRET_KEY
              value: "some-key"
            - name: TEST_VAR
              value: "prueba://$(db-service)"
          ports:
            - containerPort: 4444